### PR TITLE
Sponsorship Page

### PR DESCRIPTION
**Pull request by X-AmpleDevelopment**
created a sponsorship page, updating the index's footer. Included table view of different sponsorship tiers and links to github sponsor page

### CODE REVIEW

**Comment by mohaidarus** [comment]
Could I have a picture of both the desktop and mobile layout.

**Comment by DJKnaeckebrot** [comment]
image

@X-AmpleDevelopment the UI needs some more rework. When larger than md (ipad) you have a horizontal scrollbar.

**Comment by X-AmpleDevelopment** [comment]
Not a problem, will review today and push an update

**Comment by DJKnaeckebrot** [comment]
you might can take this a a string point if you want :)

```ejs
<!--
=========================================================
* Soft UI Dashboard - v1.0.3
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-dashboard
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <%- include('partials/preloader.ejs', {now: 'sponsor'}) %>
    <%- themeConfig?.customHtml %>
    <style>
        .card {
            width: 100%;
            height: 550px;
            text-align: center;
            border-radius: 15px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .card img {
            width: 200px;
            height: 200px;
            border-radius: 50%;
        }

        .text-gradient {
            background: linear-gradient(45deg, #007bff, #00d4ff);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        .choose-btn {
            color: #007bff;
            text-decoration: none;
            font-size: 1rem;
        }
    </style>
</head>

<body class="g-sidenav-show bg-gray-100" id="scroll">
<%- include('partials/preload.ejs') %>
<%- include('partials/sidebar.ejs', {config: config, now:'sponsor'}) %>
<div class="main-content position-relative bg-gray-100 max-height-vh-100 h-100">
    <!-- Navbar -->
    <%- include('partials/navbar.ejs', {now:'sponsor'}) %>
    <!-- End Navbar -->
    </section>
    <%
    const images = ["curved-1", "curved-2", "curved-3", "curved-4", "curved-5", "curved-6", "curved-7", "curved-8", "curved-9", "curved-10", "curved-11", "curved-12", "curved-13", "curved-14", "curved-15", "curved-16", "curved-17", "curved-18"];

    const image = images[Math.floor(Math.random() * images.length)];
    %>
    <section class="py-5 position-relative" id="mainSection">
        <div class="container">
            <div class="row mt-4 d-flex justify-content-center" id="cardContainer">
                <!-- Cards will be injected here by JavaScript -->
            </div>
        </div>
    </section>
</div>
</main>
<script>
    const sponsorshipOptions = [
        { price: '$2 P/Month', description: 'Have your bug reports prioritized', url: 'https://github.com/sponsors/Assistants-Technologies' },
        { price: '$3 P/Month', description: 'Get a Sponsor badge on your profile', url: 'https://github.com/sponsors/Assistants-Technologies' },
        { price: '$4 P/Month', description: 'Get a Personal License for your Discord-Dashboard project', url: 'https://github.com/sponsors/Assistants-Technologies' },
        { price: '$50 P/Month', description: 'Get a Production License for your Discord-Dashboard project & BE A GOAT', url: 'https://github.com/sponsors/Assistants-Technologies' },
    ];

    function createCard(option) {
        return `
            <div class="col-12 col-md-6 col-lg-4 col-xl-3 mb-4">
                <div class="card">
                    <div class="p-3">
                        <img class="img border-radius-100 max-width-200 w-100 position-relative z-index-2"
                             src="https://avatars.githubusercontent.com/u/86969968"
                             alt="Sponsor">
                    </div>
                    <hr style="margin: 0 20px;">
                    <div>
                        <div class="p-3 text-center" style="text-align: left !important; padding-top: 0 !important;">
                            <h2 class="text-gradient text-primary" style="font-size: 1.75rem; margin: 10px 0;">${option.price}</h2>
                            <p style="font-size: 1rem; color: #555;">${option.description}</p>
                            <div style="position: absolute; bottom: 15px; width: 100%; text-align: center;">
                                <a class="text-body text-bg font-weight-bold mb-0 icon-move-right choose-btn"
                                   href="${option.url}">
                                    Choose this Amount
                                    <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true" style="margin-left: 5px;"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `;
    }

    $(document).ready(function() {
        const cardContainer = $('#cardContainer');
        sponsorshipOptions.forEach(option => {
            cardContainer.append(createCard(option));
        });
    });
</script>
<script>
    let disableFunc = false;
    var win;

    function supportServer() {
        if (disableFunc) return;
        disableFunc = true;
        $('#discordButton').parent().css('overflow', 'hidden');
        $('#discordButton').animate({'margin-top': '-=50px'});
        $('#discordButton').animate({'margin-top': '+=500px', opacity: 0}, function () {
            $(this).hide();
        });
        $("#discordRocket").fadeIn();
        setTimeout(function () {
            $('#rocketDiscord').animate({'margin-top': '+=600px'}, 1);
            $("#mainSection").fadeOut();
            $("#main2").fadeOut();
            $("#getHelp").fadeOut();
        }, 1000)
        setTimeout(function () {
            setTimeout(function () {
                $('#rocketDiscord').animate({'margin-top': '+=75px'});
                $('#rocketDiscord').animate({'margin-top': '-=1000px'}, 1500);
                setTimeout(function () {
                    window.open('https://discord.gg/EdJFwNvNS9', '_blank', 'location=yes,height=1200,width=800');

                    $("#rocketDiscord").fadeOut();
                    $("#discordRocket").fadeOut();

                    setTimeout(function () {
                        disableFunc = false;
                        location.reload();
                    }, 3500)
                }, 1200)
            }, 1500)
        }, 2000);
    }


</script>


<%- include('partials/scripts.ejs', {now: "sponsor"}) %>
</body>

</html>
```

**Comment by DJKnaeckebrot** [comment]
image

**Comment by X-AmpleDevelopment** [comment]
Looks good to me! Happy for you to replace and push

**Comment by DJKnaeckebrot** [comment]
You can rework if you want, just and idea and what chatgpt spit out :D

**Comment by X-AmpleDevelopment** [comment]
ChatGPT 😂 aye, if it works it works lol

**Comment by X-AmpleDevelopment** [comment]
pushed the updated sponsor page

**Comment by DJKnaeckebrot** [comment]
Want me to merge or still working on it? :)

**Comment by X-AmpleDevelopment** [comment]
Happy to merge if you are.. will look at updates in the future

**Comment by DJKnaeckebrot** [comment]
Sure! One last thing tho: You put in the link in the footer if the footers default is replaced. Guess thats intended to no have it in the "default" footer? :D Just wanna make sure thats intended :)
Otherwise great work!

**Comment by X-AmpleDevelopment** [comment]
It is indeed intended! Appreciate the feedback

**Review by DJKnaeckebrot — APPROVED** [review]

**Pull request merged**
